import type { Metadata } from "next";
import Header from "../components/header";
import Footer from "../components/footer";
import { SiteProvider } from "@/providers/site-provider";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SiteProvider>
            <Header />
            {children}
            <Footer />
        </SiteProvider>
    );
}
