import type { Metadata } from "next";

import "./globals.css";

import { Barlow_Condensed, Be_Vietnam_Pro } from 'next/font/google'
import localFont from 'next/font/local';
import { Toaster } from "@/components/ui/sonner";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import Providers from "@/providers/providers";
import NextTopLoader from "nextjs-toploader";


const Vietnam_Pro = Be_Vietnam_Pro({ 
  subsets: ["latin"], 
  weight: ["200","300","400","500","600","700","800"],
  variable: '--font-vietnam-pro'
});

const Barlow_Condensed_Font = Barlow_Condensed({ 
  subsets: ["latin"], 
  weight: ["200","300","400","500","600","700","800"],
  variable: '--font-barlow-condensed'
});
const headingFontExtraBold = localFont({
  src: [
    {
      path: '../public/fonts/EurostileExtendedBlack.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-eurostile-extra-bold' // This creates a CSS variable
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${Vietnam_Pro.variable} ${headingFontExtraBold.variable} ${Barlow_Condensed_Font.variable} antialiased`}
      >
        <NextTopLoader color="#2563EB" />
        <Providers session={session}>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
